namespace Ordina.Application.Orders;

public record ProductImageDto(
    string Id,
    string Base64,
    string Filename,
    string Type,
    string UploadedAt,
    long? Size = null);

public record OrderProductDto(
    string Id,
    string Name,
    decimal Price,
    int Quantity,
    decimal Total,
    string Category,
    int Stock,
    string? PriceCurrency = "USD",
    Dictionary<string, object>? Attributes = null,
    decimal? Discount = null,
    string? Observations = null,
    string? AvailabilityStatus = "disponible",
    string? ManufacturingStatus = "debe_fabricar",
    string? ManufacturingProviderId = null,
    string? ManufacturingProviderName = null,
    DateTime? ManufacturingStartedAt = null,
    DateTime? ManufacturingCompletedAt = null,
    string? ManufacturingNotes = null,
    string? RefabricationReason = null,
    DateTime? RefabricatedAt = null,
    string? LocationStatus = null,
    string? DispatchOrigin = null,
    string LogisticStatus = "Generado",
    DateTime? DeliveredAt = null,
    bool? SurchargeEnabled = null,
    decimal? SurchargeAmount = null,
    string? SurchargeReason = null,
    IReadOnlyList<ProductImageDto>? Images = null,
    string? CommissionLineSource = null,
    string? CatalogProductId = null);

public record PaymentDetailsDto(
    string? PagomovilReference = null,
    string? PagomovilBank = null,
    string? PagomovilPhone = null,
    string? PagomovilDate = null,
    string? TransferenciaBank = null,
    string? TransferenciaReference = null,
    string? TransferenciaDate = null,
    string? CashAmount = null,
    string? CashCurrency = null,
    decimal? CashReceived = null,
    decimal? ExchangeRate = null,
    decimal? OriginalAmount = null,
    string? OriginalCurrency = null,
    string? AccountId = null,
    string? AccountNumber = null,
    string? Bank = null,
    string? Email = null,
    string? Wallet = null,
    string? Envia = null,
    bool IsConciliated = false,
    bool CasheaFinancedPortion = false,
    bool CardCommissionApplied = false,
    decimal? CardCommissionAmount = null);

public record PartialPaymentDto(
    string Id,
    decimal Amount,
    string Method,
    DateTime Date,
    IReadOnlyList<ProductImageDto>? Images = null,
    PaymentDetailsDto? PaymentDetails = null);

public record DeliveryServiceDto(
    bool Enabled,
    decimal? Cost = null,
    string Currency = "USD");

public record DeliveryServicesDto(
    DeliveryServiceDto? DeliveryExpress = null,
    DeliveryServiceDto? ServicioAcarreo = null,
    DeliveryServiceDto? ServicioArmado = null);

public record ExchangeRateInfoDto(
    decimal Rate,
    string EffectiveDate);

public record ExchangeRatesAtCreationDto(
    ExchangeRateInfoDto? Usd = null,
    ExchangeRateInfoDto? Eur = null);

public record OrderResponseDto(
    string Id,
    string OrderNumber,
    string ConvertedFromNumber,
    string ClientId,
    string ClientName,
    string VendorId,
    string VendorName,
    string? ReferrerId,
    string? ReferrerName,
    string? PostventaId,
    string? PostventaName,
    IReadOnlyList<OrderProductDto> Products,
    decimal Subtotal,
    decimal TaxAmount,
    decimal DeliveryCost,
    decimal Total,
    decimal? SubtotalBeforeDiscounts,
    decimal? ProductDiscountTotal,
    decimal? GeneralDiscountAmount,
    string? GeneralDiscountType,
    decimal? GeneralDiscountPercent,
    string PaymentType,
    string PaymentMethod,
    string? PaymentCondition,
    PaymentDetailsDto? PaymentDetails,
    IReadOnlyList<PartialPaymentDto>? PartialPayments,
    IReadOnlyList<PartialPaymentDto>? MixedPayments,
    decimal AppliedStoreCreditUsd,
    string? DeliveryAddress,
    bool HasDelivery,
    DeliveryServicesDto? DeliveryServices,
    string Status,
    string? Observations,
    string? DispatchObservations,
    string? DeclineReason,
    string? SaleType,
    string? DeliveryType,
    string? DeliveryZone,
    string? BaseCurrency,
    string Type,
    DateTime CreatedAt,
    DateTime? UpdatedAt);

public record CreateOrderDto(
    string ClientId,
    string ClientName,
    string VendorId,
    string VendorName,
    IReadOnlyList<OrderProductDto> Products,
    string PaymentType = "directo",
    string PaymentMethod = "Efectivo",
    decimal DeliveryCost = 0,
    string? ReferrerId = null,
    string? ReferrerName = null,
    string? PostventaId = null,
    string? PostventaName = null,
    decimal? GeneralDiscountAmount = null,
    string? GeneralDiscountType = null,
    decimal? GeneralDiscountPercent = null,
    PaymentDetailsDto? PaymentDetails = null,
    IReadOnlyList<PartialPaymentDto>? PartialPayments = null,
    IReadOnlyList<PartialPaymentDto>? MixedPayments = null,
    decimal AppliedStoreCreditUsd = 0,
    string? DeliveryAddress = null,
    bool HasDelivery = false,
    DeliveryServicesDto? DeliveryServices = null,
    string? Observations = null,
    string? SaleType = "entrega",
    string? DeliveryType = "entrega_programada",
    string? DeliveryZone = null,
    string Type = "Order",
    string? OriginalOrderId = null,
    ExchangeRatesAtCreationDto? ExchangeRatesAtCreation = null);

public record UpdateOrderDto(
    string? ClientId = null,
    string? ClientName = null,
    IReadOnlyList<OrderProductDto>? Products = null,
    string? Status = null,
    string? Observations = null,
    string? DispatchObservations = null,
    string? DeclineReason = null,
    string? PaymentType = null,
    string? PaymentMethod = null,
    PaymentDetailsDto? PaymentDetails = null,
    IReadOnlyList<PartialPaymentDto>? PartialPayments = null,
    IReadOnlyList<PartialPaymentDto>? MixedPayments = null,
    decimal? DeliveryCost = null,
    string? DeliveryAddress = null,
    bool? HasDelivery = null,
    DeliveryServicesDto? DeliveryServices = null,
    string? SaleType = null,
    string? DeliveryType = null,
    string? DeliveryZone = null);

public record ConvertBudgetDto(
    string BudgetId,
    string VendorId,
    string VendorName,
    string PaymentType = "directo",
    string PaymentMethod = "Efectivo",
    PaymentDetailsDto? PaymentDetails = null,
    IReadOnlyList<PartialPaymentDto>? PartialPayments = null);
