<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);EnableGenerateDocumentationFile</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Api\Ordina.Api.csproj" />
    <ProjectReference Include="..\..\src\Application\Ordina.Application.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Ordina.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Domain\Ordina.Domain.csproj" />
  </ItemGroup>

</Project>
